### ISSUE TITLE
[Backlog] 문의 구현

### ISSUE THREAD

**Issue by uijin7** [FastCampus-Final-Project-bizcurator-1/FinalProject-1-Backend#38]
## Description

문의 구현

자세한 설명을 나열하세요.

## Tasks

- [X] 문의 도메인 구현
- [ ] 문의 DTO 구현
- [ ] 문의 서비스 구현
- [ ] 문의 컨트롤러 구현
