### ISSUE TITLE
[Backlog]로그인/회원가입

### ISSUE THREAD

**Issue by gh934** [FastCampus-Final-Project-bizcurator-1/FinalProject-1-Backend#9]
## Description

로그인, 회원가입, 회원탈퇴 기능 구현.

## Tasks

- [x] USER 도메인 설계
- [x] 회원가입 기능
- [x] 로그인
- [x] jwt토큰 구현 및 설정
- [x] 회원탈퇴 기능
- [x] 이메일 인증 기능
